//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Option
    {
        public Option()
        {
            this.SubmitedAnswers = new HashSet<SubmitedAnswer>();
        }
    
        public int optionID { get; set; }
        public string optionContent { get; set; }
        public bool isCorrect { get; set; }
        public int questionID { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual ICollection<SubmitedAnswer> SubmitedAnswers { get; set; }
    }
}
