//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.Options = new HashSet<Option>();
            this.SubmitedAnswers = new HashSet<SubmitedAnswer>();
        }
    
        public int questionID { get; set; }
        public string questCont { get; set; }
        public int quizID { get; set; }
        public int userID { get; set; }
        public int points { get; set; }
    
        public virtual ICollection<Option> Options { get; set; }
        public virtual Quiz Quiz { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<SubmitedAnswer> SubmitedAnswers { get; set; }
    }
}
