//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quiz
    {
        public Quiz()
        {
            this.Questions = new HashSet<Question>();
            this.Scores = new HashSet<Score>();
        }
    
        public int quizID { get; set; }
        public string quizName { get; set; }
        public int userID { get; set; }
    
        public virtual ICollection<Question> Questions { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Score> Scores { get; set; }
    }
}
