//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubmitedAnswer
    {
        public int submitedAnsID { get; set; }
        public int optionID { get; set; }
        public int questionID { get; set; }
        public int userID { get; set; }
    
        public virtual Option Option { get; set; }
        public virtual Question Question { get; set; }
        public virtual User User { get; set; }
    }
}
